version: "3.9"

services:
    api:
        build: .
        ports:
            - 5000:5000
        user: framous
        volumes:
            - ../db:/var/lib/framous
            - $HOME/.aws/credentials:/home/framous/.aws/credentials:ro
